package:
  name: ortools
  version: "9.11.4210"

source:
#  url: "https://files.pythonhosted.org/packages/f6/3b/f4e1200886852c09ba4ef8664ae7ff2323ab23326e27515d4b1159230f7e/ortools-9.11.4210-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
#  sha256: "d5a17a37aeaa7d149e2fe8c8dfd5f09630ae28ad734a109ad55536605f8059df"

  url: "https://files.pythonhosted.org/packages/a8/c4/3d790fd19d7c2bb8fa6e3a9c9184aa4f1bdbec9662cfa7ed99b6325b8ecd/ortools-9.11.4210-cp311-cp311-win_amd64.whl" 
  sha256: "d9b858f0273e19f81555428d54d407428d0a70a8cb5df2c320935bb735f2c6bb"

build:
#  noarch: python
  number: 0
#  missing_dso_whitelist:
#    - '*/librt.so.1'
#    - '*/libstdc++.so.6'
#    - '*/libm.so.6'
#    - '*/libgcc_s.so.1'
#    - '*/libc.so.6'
#    - '*/ld-linux-x86-64.so.2'
#    - '*/libc.so.6'
#    - '*/libpthread.so.0'
#    - '*/libdl.so.2'

requirements:
  host:
    - python
    - pip
    - libgcc-ng # [not win]
  run:
    - python
    - libstdcxx-ng # [not win]
    - libgcc-ng # [not win]
   # - numpy  # Add any other dependencies `ortools` requires


test:
  imports:
    - ortools

about:
  home: https://github.com/google/or-tools
  license: Apache-2.0
    #  license_file: LICENSE
  summary: "Google's Operations Research tools"
  description: |
    OR-Tools is a fast, portable software suite for combinatorial optimization.
  doc_url: https://developers.google.com/optimization/
  dev_url: https://github.com/google/or-tools

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/55704
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - bkreider
