package:
  name: ortools
  version: "your_version_here"  # Specify the desired version

source:
  url: "https://files.pythonhosted.org/packages/3c/38/b2e915c4b3f3bf966d2d73e69ee4c72a09452822ea912af0a506a32e2a48/ortools-9.11.4210-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
  sha256: "03ecd32e5d760d48e59832ef6bf724f8cac95e4e40db72a7fb912abf7adcf931"

build:
  number: 0
    #  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python
    - pip
  run:
    - python
   # - numpy  # Add any other dependencies `ortools` requires

about:
  home: https://github.com/google/or-tools
  license: Apache-2.0
    #  license_file: LICENSE
  summary: "Google's Operations Research tools"
  description: |
    OR-Tools is a fast, portable software suite for combinatorial optimization.
  doc_url: https://developers.google.com/optimization/
  dev_url: https://github.com/google/or-tools

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/55704
    reason: Client request
  recipe-maintainers:
    - ianaobi
