package:
  name: ortools
  version: "your_version_here"  # Specify the desired version

source:
  url: "https://files.pythonhosted.org/packages/f6/3b/f4e1200886852c09ba4ef8664ae7ff2323ab23326e27515d4b1159230f7e/ortools-9.11.4210-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
  sha256: "d5a17a37aeaa7d149e2fe8c8dfd5f09630ae28ad734a109ad55536605f8059df"

build:
  number: 0
    #  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python
    - pip
  run:
    - python
   # - numpy  # Add any other dependencies `ortools` requires

about:
  home: https://github.com/google/or-tools
  license: Apache-2.0
    #  license_file: LICENSE
  summary: "Google's Operations Research tools"
  description: |
    OR-Tools is a fast, portable software suite for combinatorial optimization.
  doc_url: https://developers.google.com/optimization/
  dev_url: https://github.com/google/or-tools

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/55704
    reason: Client request
  recipe-maintainers:
    - ianaobi
