{% set version = "9.9" %}
# pinnings
{% set cmake = ">=3.18" %}
{% set libabseil = "20240116.2*" %}
{% set re2 = "2024-02-01" %}
{% set mypy_protobuf = "3.6.0" %}
{% set mypy = "1.14.1" %}
{% set eigen = "3.4.0" %}
{% set pybind11 = "2.13.6" %}
{% set pybind11_abseil_commit_id = "52f2739" %}
{% set pybind11_protobuf_commit_id = "3b11990" %}

package:
  name: or-tools-package
  version: {{ version }}

source:
  - url: https://github.com/google/or-tools/archive/v{{ version }}.tar.gz
    sha256: 8c17b1b5b05d925ed03685522172ca87c2912891d57a5e0d5dcaeff8f06a4698
    patches:
      - patches/0001-3.13_support.patch
      - patches/0002-add-pybind11_abseil-as-dependency.patch
      - patches/0003-s390x_cast.patch
  - url: https://github.com/pybind/pybind11_protobuf/archive/{{ pybind11_protobuf_commit_id }}.tar.gz
    sha256: 8747cbedbc9408b197858fa327b186b0340770721b9848471c040821eb10eae6
    folder: pybind11_protobuf
    patches:
      - patches/pybind11_protobuf/0001-fix-python-headers.patch
      - patches/pybind11_protobuf/0002-add-install-and-cmake-config-generation.patch
      - patches/pybind11_protobuf/0003-use-installed-abseil-protobuf-pybind11.patch
      - patches/pybind11_protobuf/0004-use-modern-findpython-module.patch
      - patches/pybind11_protobuf/0005-install-headers.patch
      - patches/pybind11_protobuf/0006-apply-or-tools-team-patch.patch
  - url: https://github.com/pybind/pybind11_abseil/archive/{{ pybind11_abseil_commit_id }}.tar.gz
    sha256: d977f05b4be67c49f3d2b4795d0daf513f7098a0261b66badb0fa573a1f01391
    folder: pybind11_abseil
    patches:
      - patches/pybind11_abseil/0001-use-installed-abseil-and-pybind11.patch
      - patches/pybind11_abseil/0002-use-modern-findpython-module.patch
      - patches/pybind11_abseil/0003-apply-or-tools-team-patch.patch
      - patches/pybind11_abseil/0004-add-cmake-target-and-config-generation.patch
      - patches/pybind11_abseil/0005-install-headers.patch

# The meta package
build:
  number: 0
  # coin-or-* rely on openblas not available on Windows
  skip: true  # [win]

requirements:
  build:
    - patch  # [not win]
  host:
    - python

outputs:
  # The core package
  - name: libortools
    script: build-cpp.sh
    build:
      run_exports:
        - {{ pin_subpackage('libortools', max_pin='x.x') }}
      ignore_run_exports_from:
        - python
      missing_dso_whitelist:  # [s390x or (osx and x86_64)]
        - '$RPATH/ld64.so.1'  # [s390x]
        # Conda build failing to identify this shared library.
        # A test has been added instead for osx-64
        - '*/libortools.9.dylib'  # [osx and x86_64]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake {{ cmake }}
        - ninja
        - pkg-config
        - patch  # [not win]
      host:
        - eigen {{ eigen }}
        - libabseil {{ libabseil }}
        - libprotobuf {{ libprotobuf }}
        - re2 {{ re2 }}
        - zlib
        # coin or deps
        - coin-or-utils 2.11.6
        - coin-or-osi 0.108.7
        - coin-or-clp 1.17.7
        - coin-or-cgl 0.60.5
        - coin-or-cbc 2.10.7
        # Source: https://github.com/google/or-tools/blob/stable/cmake/dependencies/CMakeLists.txt
        # fake python dependency to avoid conda-smithy collapsing the builds per arch;
        # we can remove this once we manage to base the python bindings on libortools
        - python
      run_constrained:
        # make sure we don't co-install with old version of previous package name
        - ortools-cpp ={{ version }}
    test:
      commands:
        - test -f $PREFIX/lib/libortools${SHLIB_EXT}
        - test -f $PREFIX/lib/cmake/ortools/ortoolsTargets.cmake
        - test -f $PREFIX/lib/cmake/ortools/ortoolsConfig.cmake
        - test -f $PREFIX/include/ortools_export.h
        - test -f $PREFIX/include/ortools/algorithms/dense_doubly_linked_list.h

  # for compatibility with previous output "ortools-cpp"
  - name: ortools-cpp
    build:
      missing_dso_whitelist:  # [s390x or (osx and x86_64)]
        - '$RPATH/ld64.so.1'  # [s390x]
        # Conda build failing to identify this shared library.
        # A test has been added instead for osx-64
        - '*/libortools.9.dylib'  # [osx and x86_64]
      run_exports:
        - {{ pin_subpackage('libortools', max_pin='x.x') }}
    requirements:
      host:
        - {{ pin_subpackage('libortools', exact=True) }}
      run:
        - {{ pin_subpackage('libortools', exact=True) }}
    test:
      commands:
        # just make sure that everything worked,
        # the rest are already tested in libortools
        - test -f $PREFIX/lib/libortools${SHLIB_EXT}

  # The python package.
  - name: ortools-python
    script: build-python.sh
    build:
      missing_dso_whitelist:  # [s390x or (osx and x86_64)]
        - '$RPATH/ld64.so.1'  # [s390x]
        # Conda build failing to identify this shared library.
        # A test has been added instead for osx-64
        - '*/libortools.9.dylib'  # [osx and x86_64]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake {{ cmake }}
        - ninja
        - mypy-protobuf {{ mypy_protobuf }}
        - mypy {{ mypy }}
        - pkg-config
        - swig >=4.0
        - patch  # [not win]
        - python
      host:
        - python
        - pip
        - wheel
        - setuptools
        - mypy-protobuf {{ mypy_protobuf }}
        - mypy {{ mypy }}
        # C/C++ deps
        - eigen {{ eigen }}
        - libabseil {{ libabseil }}
        - libprotobuf {{ libprotobuf }}
        - libprotobuf-python-headers {{ libprotobuf }}
        - pybind11 {{ pybind11 }}
        # - pybind11_protobuf 3b11990
        - {{ pin_subpackage('pybind11_protobuf', exact=True) }}
        # - pybind11_abseil 52f2739
        - {{ pin_subpackage('pybind11_abseil', exact=True) }}
        - re2 {{ re2 }}
        - zlib
        # coin or deps
        - coin-or-utils 2.11.6
        - coin-or-osi 0.108.7
        - coin-or-clp 1.17.7
        - coin-or-cgl 0.60.5
        - coin-or-cbc 2.10.7
        # Source:
        # https://github.com/google/or-tools/blob/v9.9/ortools/python/setup.py.in#L44
        - absl-py 2.1.0
        - numpy 2.0.1
        - pandas 2.2.3
        - protobuf {{ libprotobuf }}
        - immutabledict 4.2.0
      run:
        - python
        - mypy-protobuf {{ mypy_protobuf }}
        # Source: https://github.com/google/or-tools/blob/stable/ortools/python/setup.py.in#L44
        - absl-py >=2.0.0
        - {{ pin_compatible('numpy') }}
        - pandas >=2.0.0
        - protobuf {{ libprotobuf }}
        - immutabledict >=3.0.0
        # - pybind11_protobuf 3b11990
        - {{ pin_subpackage('pybind11_protobuf', exact=True) }}
        # - pybind11_abseil 52f2739
        - {{ pin_subpackage('pybind11_abseil', exact=True) }}
    test:
      requires:
        - pip
        - scipy >=1.10
      imports:
        - ortools
        - ortools.linear_solver.pywraplp
      commands:
        - pip check
        - ${PYTHON} cmake/samples/python/sample.py
        - ${PYTHON} ortools/sat/samples/assignment_sat.py
        - test -f ${SP_DIR}/ortools/.libs/libortools.9.dylib  # [osx and x86_64]
      source_files:
        - cmake/samples/python/sample.py
        - ortools/sat/samples/assignment_sat.py

  # The pybind11_protobuf package, used by ortools-python.
  - name: pybind11_protobuf
    # The version is a placeholder, to avoid setting its version
    # like the rest of the recipe (e.g. 9.9). The commit id is
    # used (see above).
    version: {{ pybind11_protobuf_commit_id }}
    script: build-pybind11_protobuf.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake {{ cmake }}
        - ninja
        - python
      host:
        - python
        # These must align with ortools-python,
        # rather than upstream
        - libabseil {{ libabseil }}
        - libprotobuf {{ libprotobuf }}
        - libprotobuf-python-headers {{ libprotobuf }}
        - pybind11 {{ pybind11 }}
      run:
        - python
    test:
      commands:
        # static libraries
        - test -f $PREFIX/lib/libpybind11_native_proto_caster.a
        # shared libraries
        - test -f $PREFIX/lib/pybind11_proto_utils*${SHLIB_EXT}
        - test -f $PREFIX/lib/libpybind11_wrapped_proto_caster${SHLIB_EXT}
        # config and targets
        - test -f $PREFIX/lib/cmake/pybind11_protobuf/pybind11_protobufTargets.cmake
        - test -f $PREFIX/lib/cmake/pybind11_protobuf/pybind11_protobufConfig.cmake
        # key headers
        - test -f $PREFIX/include/pybind11_protobuf/check_unknown_fields.h
        - test -f $PREFIX/include/pybind11_protobuf/wrapped_proto_caster.h
        - test -f $PREFIX/include/pybind11_protobuf/native_proto_caster.h

  # The pybind11_abseil package, used by ortools-python
  - name: pybind11_abseil
    # The version is a placeholder, to avoid setting its version
    # like the rest of the recipe (e.g. 9.9). The commit id is
    # used (see above).
    version: {{ pybind11_abseil_commit_id }}
    script: build-pybind11_abseil.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake {{ cmake }}
        - ninja
        - python
      host:
        - python
        # These must align with ortools-python,
        # rather than upstream
        - libabseil {{ libabseil }}
        - libprotobuf {{ libprotobuf }}
        - pybind11 {{ pybind11 }}
      run:
        - python
        - absl-py
        - numpy >=1.13.3
    test:
      imports:
        - pybind11_abseil.status
        - pybind11_abseil.ok_status_singleton
      commands:
        # shared libraries
        - test -f $SP_DIR/pybind11_abseil/status.*${SHLIB_EXT}
        - test -f $SP_DIR/pybind11_abseil/ok_status_singleton.*${SHLIB_EXT}
        - test -f $PREFIX/lib/libabsl_status.so
        - test -f $PREFIX/lib/libabsl_base.so
        - test -f $PREFIX/lib/libabsl_log_entry.so
        # config and targets
        - test -f $PREFIX/lib/cmake/pybind11_abseil/pybind11_abseilTargets.cmake
        - test -f $PREFIX/lib/cmake/pybind11_abseil/pybind11_abseilConfig.cmake
        # key headers
        - test -f $PREFIX/include/pybind11_abseil/status_caster.h
        - test -f $PREFIX/include/pybind11_abseil/absl_casters.h

about:
  home: https://developers.google.com/optimization
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Operations Research Tools (or-tools) python package
  description: |
    OR-Tools is an open source software suite for optimization, tuned for tackling
    the world's toughest problems in vehicle routing, flows, integer and linear
    programming, and constraint programming.

    After modeling your problem in the programming language of your choice, you
    can use any of a half dozen solvers to solve it: commercial solvers such as
    Gurobi or CPLEX, or open-source solvers such as SCIP, GLPK, or Google's GLOP
    and award-winning CP-SAT.
  dev_url: https://github.com/google/or-tools
  doc_url: https://developers.google.com/optimization

extra:
  recipe-maintainers:
    - wolfv
    - BastianZim
    - h-vetinari
  feedstock-name: or-tools
