package:
  name: ortools
  version: "your_version_here"  # Specify the desired version

source:
  url: "https://files.pythonhosted.org/packages/a8/f8/08ee137d4f586725b8499866ed55f92628b534939dfc0e98ab99ac5f4ca7/ortools-9.11.4210-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
  sha256: "9c3693f0cb07ee0b5d36c4817bcfe05a745e3a613798a2ed62eb998d7fff979c"

build:
  number: 0
  missing_dso_whitelist:
    - '*/librt.so.1'
    - '*/libstdc++.so.6'
    - '*/libm.so.6'
    - '*/libgcc_s.so.1'
    - '*/libc.so.6'
    - '*/ld-linux-x86-64.so.2'
    - '*/libc.so.6'
    - '*/libpthread.so.0'
    - '*/libdl.so.2'

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libstdcxx-ng
    - libgcc-ng
   # - numpy  # Add any other dependencies `ortools` requires

about:
  home: https://github.com/google/or-tools
  license: Apache-2.0
    #  license_file: LICENSE
  summary: "Google's Operations Research tools"
  description: |
    OR-Tools is a fast, portable software suite for combinatorial optimization.
  doc_url: https://developers.google.com/optimization/
  dev_url: https://github.com/google/or-tools

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/55704
    reason: Client request
  recipe-maintainers:
    - ianaobi
