{% set name = "or-tools" %}
{% set version = "9.15" %}

package:
  name: {{ name }}-package
  version: {{ version }}

source:
  - url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 6395a00a97ff30af878ee8d7fd5ad0ab1c7844f7219182c6d71acbee1b5f3026
    patches:
      - patches/fix-dll-injection.patch  # [win]

# The meta package
build:
  number: 0

requirements:
  build:
    # git used for vendored pybind11_protobuf and pybind11_abseil
    - git
  host:
    - python

outputs:
  # The core package
  - name: libortools
    script: build-cpp.sh   # [not win]
    script: build-cpp.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libortools', max_pin='x.x') }}
      ignore_run_exports_from:
        - python
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja-base
        - pkg-config
      host:
        - eigen {{ eigen }}
        - libabseil {{ libabseil }}
        - libprotobuf {{ libprotobuf }}
        - re2 {{ re2 }}
        - zlib {{ zlib }}
        - bzip2 {{ bzip2 }}
        # coin or deps
        - coin-or-utils
        - coin-or-osi
        - coin-or-clp
        - coin-or-cgl
        - coin-or-cbc
        # Needed for coin-or-*
        - mkl-devel {{ mkl }}  # [win]
        # Source: https://github.com/google/or-tools/blob/stable/cmake/dependencies/CMakeLists.txt
        # fake python dependency to avoid conda-smithy collapsing the builds per arch;
        # we can remove this once we manage to base the python bindings on libortools
        - python
      run_constrained:
        # make sure we don't co-install with old version of previous package name
        - ortools-cpp ={{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libortools${SHLIB_EXT}                                     # [unix]
        - test -f ${PREFIX}/lib/cmake/ortools/ortoolsTargets.cmake                         # [unix]
        - test -f ${PREFIX}/lib/cmake/ortools/ortoolsConfig.cmake                          # [unix]
        - test -f ${PREFIX}/include/ortools_export.h                                       # [unix]
        - test -f ${PREFIX}/include/ortools/algorithms/dense_doubly_linked_list.h          # [unix]
        - if not exist %LIBRARY_LIB%/ortools.lib exit 1                                    # [win]
        - if not exist %LIBRARY_LIB%/cmake/ortools/ortoolsTargets.cmake exit 1             # [win]
        - if not exist %LIBRARY_LIB%/cmake/ortools/ortoolsConfig.cmake exit 1              # [win]
        - if not exist %LIBRARY_INC%/ortools_export.h exit 1                               # [win]
        - if not exist %LIBRARY_INC%/ortools/algorithms/dense_doubly_linked_list.h exit 1  # [win]

  # for compatibility with previous output "ortools-cpp"
  - name: ortools-cpp
    build:
      run_exports:
        - {{ pin_subpackage('libortools', max_pin='x.x') }}
    requirements:
      host:
        - {{ pin_subpackage('libortools', exact=True) }}
      run:
        - {{ pin_subpackage('libortools', exact=True) }}
    test:
      commands:
        # just make sure that everything worked,
        # the rest are already tested in libortools
        - test -f ${PREFIX}/lib/libortools${SHLIB_EXT}   # [unix]
        - if not exist %LIBRARY_LIB%/ortools.lib exit 1  # [win]

  # The python package.
  - name: ortools-python
    script: build-python.sh   # [not win]
    script: build-python.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja-base
        - mypy-protobuf
        - mypy
        - pkg-config
        - swig >=4.0
        - python
        - git
      host:
        - pip
        - python
        - wheel
        - setuptools
        - mypy-protobuf
        - mypy
        # C/C++ deps
        - eigen {{ eigen }}
        - libabseil {{ libabseil }}
        - libprotobuf {{ libprotobuf }}
        - libprotobuf-python-headers {{ libprotobuf }}
        - pybind11
        - re2 {{ re2 }}
        - zlib {{ zlib }}
        - bzip2 {{ bzip2 }}
        # coin or deps
        - coin-or-utils
        - coin-or-osi
        - coin-or-clp
        - coin-or-cgl
        - coin-or-cbc
        # Needed for coin-or-* stack
        - mkl-devel {{ mkl }}  # [win]
        # Source:
        # https://github.com/google/or-tools/blob/v9.9/ortools/python/setup.py.in#L44
        - absl-py
        - numpy {{ numpy }}
        - pandas
        - protobuf
        - immutabledict
      run:
        - python
        # Source: https://github.com/google/or-tools/blob/stable/ortools/python/setup.py.in#L44
        - numpy
        - absl-py >=2.0.0
        - pandas >=2.0.0
        - protobuf {{ libprotobuf }}
        - typing-extensions >=4.12
        - immutabledict >=3.0.0
    test:
      source_files:
        - cmake/samples/python/sample.py
        - ortools/sat/samples/assignment_sat.py
      requires:
        - pip
        - scipy >=1.10
      imports:
        - ortools
        - ortools.algorithms.python.knapsack_solver
        - ortools.linear_solver._pywraplp
        - ortools.linear_solver.python.model_builder_helper
        - ortools.sat.python.cp_model_helper
        - ortools.constraint_solver._pywrapcp
        - ortools.graph.python.max_flow
        - ortools.graph.python.min_cost_flow
        - ortools.math_opt.core.python.solver
        - ortools.util.python.sorted_interval_list
      commands:
        - pip check
        - python cmake/samples/python/sample.py
        - python ortools/sat/samples/assignment_sat.py

about:
  home: https://developers.google.com/optimization
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Operations Research Tools (or-tools) python package
  description: |
    OR-Tools is an open source software suite for optimization, tuned for tackling
    the world's toughest problems in vehicle routing, flows, integer and linear
    programming, and constraint programming.

    After modeling your problem in the programming language of your choice, you
    can use any of a half dozen solvers to solve it: commercial solvers such as
    Gurobi or CPLEX, or open-source solvers such as SCIP, GLPK, or Google's GLOP
    and award-winning CP-SAT.
  dev_url: https://github.com/google/or-tools
  doc_url: https://developers.google.com/optimization

extra:
  recipe-maintainers:
    - wolfv
    - BastianZim
    - h-vetinari
  feedstock-name: or-tools
